// @ts-nocheck
/**
 * Books API
 * The Books API provides information about book reviews and The New York Times Best Sellers lists.  ## Best Sellers Lists Services ### List Names The lists/names service returns a list of all the NYT Best Sellers Lists.  Some lists are published weekly and others monthly.  The response includes when each list was first published and last published.  ``` /lists/names.json ```  ### List Data  The lists/{date}/{name} service returns the books on the best sellers list for the specified date and list name.  ``` /lists/2019-01-20/hardcover-fiction.json ```  Use \"current\" for {date} to get the latest list. ``` /lists/current/hardcover-fiction.json ```  ## Book Reviews Services  The book reviews service lets you get NYT book review by author, ISBN, or title.  ``` /reviews.json?author=Michelle+Obama ```  ``` /reviews.json?isbn=9781524763138 ```  ``` /reviews.json?title=Becoming ```  ## Example Calls  ``` https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api-key=yourkey ```  ``` https://api.nytimes.com/svc/books/v3/reviews.json?author=Stephen+King&api-key=yourkey ``` 
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InlineResponse2001ResultsBooks } from './inlineResponse2001ResultsBooks';

export class InlineResponse2001Results {
    'listName'?: string;
    'bestsellersDate'?: string;
    'publishedDate'?: string;
    'displayName'?: string;
    'normalListEndsAt'?: number;
    'updated'?: string;
    'books'?: Array<InlineResponse2001ResultsBooks>;
    'corrections'?: Array<object>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string, baseName: string, type: string }> = [
        {
            "name": "listName",
            "baseName": "list_name",
            "type": "string"
        },
        {
            "name": "bestsellersDate",
            "baseName": "bestsellers_date",
            "type": "string"
        },
        {
            "name": "publishedDate",
            "baseName": "published_date",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string"
        },
        {
            "name": "normalListEndsAt",
            "baseName": "normal_list_ends_at",
            "type": "number"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "string"
        },
        {
            "name": "books",
            "baseName": "books",
            "type": "Array<InlineResponse2001ResultsBooks>"
        },
        {
            "name": "corrections",
            "baseName": "corrections",
            "type": "Array<object>"
        }];

    static getAttributeTypeMap() {
        return InlineResponse2001Results.attributeTypeMap;
    }
}

