// @ts-nocheck
/**
 * Books API
 * The Books API provides information about book reviews and The New York Times Best Sellers lists.  ## Best Sellers Lists Services ### List Names The lists/names service returns a list of all the NYT Best Sellers Lists.  Some lists are published weekly and others monthly.  The response includes when each list was first published and last published.  ``` /lists/names.json ```  ### List Data  The lists/{date}/{name} service returns the books on the best sellers list for the specified date and list name.  ``` /lists/2019-01-20/hardcover-fiction.json ```  Use \"current\" for {date} to get the latest list. ``` /lists/current/hardcover-fiction.json ```  ## Book Reviews Services  The book reviews service lets you get NYT book review by author, ISBN, or title.  ``` /reviews.json?author=Michelle+Obama ```  ``` /reviews.json?isbn=9781524763138 ```  ``` /reviews.json?title=Becoming ```  ## Example Calls  ``` https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api-key=yourkey ```  ``` https://api.nytimes.com/svc/books/v3/reviews.json?author=Stephen+King&api-key=yourkey ``` 
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse2002Results {
    'listName'?: string;
    'displayName'?: string;
    'listNameEncoded'?: string;
    'oldestPublishedDate'?: string;
    'newestPublishedDate'?: string;
    'updated'?: InlineResponse2002Results.UpdatedEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string, baseName: string, type: string }> = [
        {
            "name": "listName",
            "baseName": "list_name",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string"
        },
        {
            "name": "listNameEncoded",
            "baseName": "list_name_encoded",
            "type": "string"
        },
        {
            "name": "oldestPublishedDate",
            "baseName": "oldest_published_date",
            "type": "string"
        },
        {
            "name": "newestPublishedDate",
            "baseName": "newest_published_date",
            "type": "string"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "InlineResponse2002Results.UpdatedEnum"
        }];

    static getAttributeTypeMap() {
        return InlineResponse2002Results.attributeTypeMap;
    }
}

export namespace InlineResponse2002Results {
    export enum UpdatedEnum {
        Weekly = <any>'WEEKLY',
        Monthly = <any>'MONTHLY'
    }
}
